name: MySQL
tabs:
- name: main
  label: Config
  sections:
  - name: section_one
    contents: 
    - type: heading
      label: Root Settings
    - type: base-64-password
      variable: auth.password
      label: Password (default = mysqlftw)
      required: true
      settings:
        default: bXlzcWxmdHc=
  - name: resource
    contents:
    - type: heading
      label: Resource Allocation
    - type: number-input
      variable: resources.storage
      required: true
      label: Storage (Gi)
      settings:
        default: 1
        unit: Gi