name: Metabase
hasSource: false
tabs:
- name: resources
  label: Computing resources
  sections:
  - name: main_section
    contents:
    - type: heading
      label: Resources
    - type: subtitle
      label: Configure resources assigned to this container.
    - type: number-input
      label: RAM
      variable: resources.requests.memory
      settings:
        unit: Mi
        default: 256
    - type: number-input
      label: CPU
      variable: resources.requests.cpu
      settings:
        unit: m
        default: 100