name: Metabase
hasSource: true
tabs:
- name: main
  label: Main Settings
  sections:
  - name: domain_toggle
    show_if: service.exposed
    contents:
    - type: subtitle
      label: Assign custom domain to your deployment. You must first create an A record in your domain provider that points to your cluster's IP address for this.
    - type: checkbox
      variable: custom_domain
      label: Configure Custom Domain
      settings:
        default: false
  - name: domain_name
    show_if: custom_domain
    contents:
    - type: string-input
      variable: ingress.host
      label: Domain Name
- name: resources
  label: Computing resources
  sections:
  - name: main_section
    contents:
    - type: heading
      label: Resources
    - type: subtitle
      label: Configure resources assigned to this container.
    - type: number-input
      label: RAM
      variable: resources.requests.memory
      settings:
        unit: Mi
        default: 256
    - type: number-input
      label: CPU
      variable: resources.requests.cpu
      settings:
        unit: m
        default: 100