{{- if .Values.ingress.enabled -}}
{{- $fullName := include "docker-template.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "docker-template.labels" . | nindent 4 }}
  annotations:
    {{- if eq .Values.ingress.provider "aws"}}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- else if eq .Values.ingress.provider "digitalocean"}}
    cert-manager.io/cluster-issuer: letsencrypt-prod
    {{- else }}
    {{ end }}
spec:
  {{ if .Values.ingress.host }}
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: tls-secret
  {{ end }}
  rules:
    {{ if eq .Values.ingress.host "" }}
    - http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{ else }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
    {{ end }}
  {{- end }}
